INSERT INTO SAR_AUTHORITY (NAME) VALUES ('PROVIDER');
INSERT INTO SAR_AUTHORITY (NAME) VALUES ('DELIVER');
INSERT INTO SAR_AUTHORITY (NAME) VALUES ('CUSTOMER');
INSERT INTO SAR_AUTHORITY (NAME) VALUES ('ADMINISTRATOR');
COMMIT;