INSERT INTO SAR_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ADMINISTRATOR');
INSERT INTO SAR_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (2, 'PROVIDER');
INSERT INTO SAR_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (3, 'CUSTOMER');
INSERT INTO SAR_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (4, 'DELIVER');
COMMIT;