INSERT INTO SAR_USER (ID,ACTIVATED,EMAIL,FIRST_NAME,LAST_NAME,LOGIN,PASSWORD_HASH,RESET_DATE) VALUES (1,1,'aaa','aaa','aaa','aaa','aaa',SYSDATE);
INSERT INTO SAR_USER (ID,ACTIVATED,EMAIL,FIRST_NAME,LAST_NAME,LOGIN,PASSWORD_HASH,RESET_DATE) VALUES (2,1,'bbb','bbb','bbb','bbb','bbb',SYSDATE);
INSERT INTO SAR_USER (ID,ACTIVATED,EMAIL,FIRST_NAME,LAST_NAME,LOGIN,PASSWORD_HASH,RESET_DATE) VALUES (3,1,'ccc','ccc','ccc','ccc','ccc',SYSDATE);
INSERT INTO SAR_USER (ID,ACTIVATED,EMAIL,FIRST_NAME,LAST_NAME,LOGIN,PASSWORD_HASH,RESET_DATE) VALUES (4,1,'ddd','ddd','ddd','ddd','ddd',SYSDATE);
COMMIT;