INSERT INTO SAR_PRODUCT (ID,NAME,DESCRIPTION,PRICE,PROVIDER) VALUES (1,'PRODUCT1','PRODUCT1',10,1);
INSERT INTO SAR_PRODUCT (ID,NAME,DESCRIPTION,PRICE,PROVIDER) VALUES (2,'PRODUCT2','PRODUCT2',10,2);
INSERT INTO SAR_PRODUCT (ID,NAME,DESCRIPTION,PRICE,PROVIDER) VALUES (3,'PRODUCT3','PRODUCT3',10,3);
INSERT INTO SAR_PRODUCT (ID,NAME,DESCRIPTION,PRICE,PROVIDER) VALUES (4,'PRODUCT4','PRODUCT4',10,4);
COMMIT;